[package]
name = "worst"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"
rq = { package = "reqwest", features = [ "blocking", "json" ], version = "0.12.4" }
serde = { version = "1.0.203", features = [ "derive" ] }
serde_json = "1.0.117"
